<a href="https://colab.research.google.com/github/imbhavi247/Cognitive-Assignments/blob/main/Assignment_4_Cognitive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

# a) Addition of 2 in all the elements
addition_result = array + 2

# b) Multiply 3 with all the elements
multiplication_result = array * 3

# c) Divide every element by 2
division_result = array / 2

print("Original array:", array)
print("After addition of 2:", addition_result)
print("After multiplication by 3:", multiplication_result)
print("After division by 2:", division_result)


Original array: [1 2 3 4 5]
After addition of 2: [3 4 5 6 7]
After multiplication by 3: [ 3  6  9 12 15]
After division by 2: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent_value(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent = values[max_count_index]
    indices = np.where(arr == most_frequent)[0]
    return most_frequent, indices

most_frequent_x, indices_x = most_frequent_value(x)
print("Array x:", x)
print("Most frequent value in x:", most_frequent_x)
print("Indices of most frequent value in x:", indices_x)

most_frequent_y, indices_y = most_frequent_value(y)
print("Array y:", y)
print("Most frequent value in y:", most_frequent_y)
print("Indices of most frequent value in y:", indices_y)


Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column


In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

element = arr[0, 1]

print("Array:")
print(arr)
print("Element in 1st row, 2nd column:", element)


Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element in 1st row, 2nd column: 20


b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

element = arr[2, 0]

print("Array:")
print(arr)
print("Element in 3rd row, 1st column:", element)


Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element in 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?


In [ ]:
import numpy as np

ujjwal = np.linspace(10, 100, 25)

print("Dimensions of the array:", ujjwal.ndim)

print("Shape of the array:", ujjwal.shape)

print("Total elements in the array:", ujjwal.size)

print("Data type of each element:", ujjwal.dtype)

print("Total number of bytes consumed by the array:", ujjwal.nbytes)

transpose_array = ujjwal.reshape((5, 5)).T
print("Transpose of the array using reshape() and T:")
print(transpose_array)

can_transpose_with_T = (transpose_array == ujjwal.reshape((5, 5)).T).all()
print("Can we transpose the array with T attribute directly?:", can_transpose_with_T)


Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200
Transpose of the array using reshape() and T:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Can we transpose the array with T attribute directly?: True


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [3]:
import numpy as np

ucs420_ujjwal = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

mean_value = np.mean(ucs420_ujjwal)
median_value = np.median(ucs420_ujjwal)
max_value = np.max(ucs420_ujjwal)
min_value = np.min(ucs420_ujjwal)
unique_elements = np.unique(ucs420_ujjwal)

print("Original array (ucs420_ujjwal):")
print(ucs420_ujjwal)
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

reshaped_ucs420_ujjwal = ucs420_ujjwal.reshape(4, 3)
print("\nReshaped array (reshaped_ucs420_ujjwal):")
print(reshaped_ucs420_ujjwal)

resized_ucs420_ujjwal = np.resize(ucs420_ujjwal, (2, 3))
print("\nResized array (resized_ucs420_ujjwal):")
print(resized_ucs420_ujjwal)


Original array (ucs420_ujjwal):
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (reshaped_ucs420_ujjwal):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (resized_ucs420_ujjwal):
[[10 20 30]
 [40 50 60]]
